package mate.academy.security;

import static org.mockito.ArgumentMatchers.any;

import java.util.Optional;
import mate.academy.exception.AuthenticationException;
import mate.academy.model.Role;
import mate.academy.model.User;
import mate.academy.service.RoleService;
import mate.academy.service.UserService;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

class AuthenticationServiceImplTest {
    private static final String EMAIL = "bob@i.ua";
    private static final String PASSWORD = "1234";
    private static User bob;
    private AuthenticationService authenticationService;
    private UserService userService;
    private RoleService roleService;
    private PasswordEncoder passwordEncoder;

    @BeforeEach
    void setUp() {
        userService = Mockito.mock(UserService.class);
        roleService = Mockito.mock(RoleService.class);
        passwordEncoder = new BCryptPasswordEncoder();
        authenticationService
                = new AuthenticationServiceImpl(userService, roleService, passwordEncoder);
        bob = new User();
        bob.setPassword(passwordEncoder.encode(PASSWORD));
        bob.setEmail(EMAIL);
    }

    @Test
    void register_ok() throws AuthenticationException {
        Mockito.when(roleService.getRoleByName("USER"))
                .thenReturn(new Role(Role.RoleName.USER));
        Mockito.when(userService.save(any())).thenAnswer(invocation -> invocation.getArgument(0));
        User actual = authenticationService.register(EMAIL, PASSWORD);
        Assertions.assertNotNull(actual, "Shouldn't return null");
        Assertions.assertEquals(EMAIL, actual.getEmail(),
                String.format("Should return user with email: %s, but was: %S",
                        EMAIL, actual.getEmail()));
    }

    @Test
    void register_theSameUserNotOk() throws AuthenticationException {
        Mockito.when(userService.findByEmail(EMAIL))
                .thenReturn(Optional.of(new User(EMAIL, PASSWORD)));
        Mockito.when(userService.save(any()))
                .thenAnswer(invocation -> invocation.getArgument(0));
        AuthenticationException thrown
                = Assertions.assertThrows(AuthenticationException.class, () -> {
                    authenticationService.register(EMAIL, PASSWORD);
                });
        Assertions.assertEquals("Authentication exception occur,"
                        + " user with such email already exist", thrown.getMessage(),
                "Expected to receive Exception with message"
                        + " \"Authentication exception occur, "
                        + "user with such email already exist\","
                        + " but was: " + thrown.getMessage()
                        + " with exception: " + thrown.getCause());
    }

    @Test
    void login_ok() throws AuthenticationException {
        Mockito.when(userService.findByEmail(EMAIL)).thenReturn(Optional.of(bob));
        User actual = authenticationService.login(EMAIL, PASSWORD);
        Assertions.assertNotNull(actual);
        Assertions.assertEquals(bob, actual);
    }
}
